[package]
name = "ds5-bridge-config-tauri"
version = "0.0.212"
description = "DS5 Bridge Config Manager"
authors = ["minse"]
edition = "2024"
license = "MIT"

[lib]
name = "ds5_bridge_config_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
hidapi = { version = "2.6", default-features = false, features = ["windows-native"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.9.4", features = [] }
thiserror = "2"
toml = "0.9"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
tokio = { version = "1", features = ["time"] }
windows-sys = { version = "0.59", features = ["Win32_Storage_FileSystem", "Win32_System_Registry"] }
serialport = "4.3"
lazy_static = "1.5.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
